In [25]:
import pandas as pd
import numpy as np

In [85]:
data = pd.read_csv('heart-disease.csv')
display(data.head())

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

array([[ 63. ,   1. ,   3. , 145. , 233. ,   1. ,   0. , 150. ,   0. ,
          2.3,   0. ,   0. ,   1. ,   1. ],
       [ 37. ,   1. ,   2. , 130. , 250. ,   0. ,   1. , 187. ,   0. ,
          3.5,   0. ,   0. ,   2. ,   1. ]])

In [63]:
X = data.drop("target", axis=1)
Y = data['target']

In [83]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# clf.get_params()

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape
 

((227, 13), (76, 13), (227,), (76,))

In [94]:
clf.fit(X_train,y_train);

In [95]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
39    65    0   2       160   360    0        0      151      0      0.8   
154   39    0   2       138   220    0        1      152      0      0.0   
157   35    1   1       122   192    0        1      174      0      0.0   
80    41    1   2       112   250    0        1      179      0      0.0   
288   57    1   0       110   335    0        1      143      1      3.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
72    29    1   1       130   204    0        0      202      0      0.0   
282   59    1   2       126   218    1        1      134      0      2.2   
73    51    1   0       140   261    0        0      186      1      0.0   
213   61    0   0       145   307    0        0      146      1      1.0   
134   41    0   1       126   306    0        1      163      0      0.0   

     slope  ca  thal  
39       2   0     2  
154      1   0     2  
157      2   0     2  
80       2   0     2  
288      1   1     3  
..     ...  ..   ...  
72       2   0     2  
282      1   1     1  
73       2   0     2  
213      1   0     3  
134      2   0     2  

[76 rows x 13 columns]

In [105]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
39    65    0   2       160   360    0        0      151      0      0.8   
154   39    0   2       138   220    0        1      152      0      0.0   
157   35    1   1       122   192    0        1      174      0      0.0   
80    41    1   2       112   250    0        1      179      0      0.0   
288   57    1   0       110   335    0        1      143      1      3.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
72    29    1   1       130   204    0        0      202      0      0.0   
282   59    1   2       126   218    1        1      134      0      2.2   
73    51    1   0       140   261    0        0      186      1      0.0   
213   61    0   0       145   307    0        0      146      1      1.0   
134   41    0   1       126   306    0        1      163      0      0.0   

     slope  ca  thal  
39       2   0     2  
154      1   0     2  
157      2   0     2  
80       2   0     2  
288      1   1     3  
..     ...  ..   ...  
72       2   0     2  
282      1   1     1  
73       2   0     2  
213      1   0     3  
134      2   0     2  

[76 rows x 13 columns]

In [96]:
y_preds = clf.predict(X_test)

In [111]:
y_preds



array([1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [112]:
# clf.predict()

In [98]:
clf.score(X_train,y_train)

1.0

In [99]:
clf.score(X_test,y_test)

0.868421052631579

In [100]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.93      0.76      0.83        33
           1       0.84      0.95      0.89        43

    accuracy                           0.87        76
   macro avg       0.88      0.86      0.86        76
weighted avg       0.88      0.87      0.87        76



In [102]:
confusion_matrix(y_test, y_preds)

array([[25,  8],
       [ 2, 41]], dtype=int64)

In [101]:
accuracy_score(y_test, y_preds)

0.868421052631579

In [103]:
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {clf.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 20 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 30 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 40 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 50 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 60 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 70 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 80 estimators...
Model accruacy on test set: 0.868421052631579

Trying model with 90 estimators...
Model accruacy on test set: 0.868421052631579



In [104]:
from sklearn.model_selection import cross_val_score

np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5)) * 100}%")
    print("")


Trying model with 10 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 78.53551912568305%

Trying model with 20 estimators...
Model accruacy on test set: 0.8421052631578947
Cross-validation score: 79.84699453551912%

Trying model with 30 estimators...
Model accruacy on test set: 0.7894736842105263
Cross-validation score: 80.50819672131148%

Trying model with 40 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 82.15300546448088%

Trying model with 50 estimators...
Model accruacy on test set: 0.8421052631578947
Cross-validation score: 81.1639344262295%

Trying model with 60 estimators...
Model accruacy on test set: 0.8552631578947368
Cross-validation score: 83.47540983606557%

Trying model with 70 estimators...
Model accruacy on test set: 0.8421052631578947
Cross-validation score: 81.83060109289617%

Trying model with 80 estimators...
Model accruacy on test set: 0.868421052631579
Cross-validation score: 82.81420765027

In [106]:
import pickle

pickle.dump(clf, open("rdm_forst_model_1.pk1", "wb"))